### ISSUE TITLE
Document how to get the pdbs?

### ISSUE THREAD

**Issue by EvanCarroll** [arvindshmicrosoft/SQLCallStackResolver#2]
It seems lists of PDBs are offered and scripts to download them. It's not clear how the PDBs are discovered. I would be interested in that.

**Comment by arvindshmicrosoft** [comment]
Hi Evan - you can obtain the script for a given build of SQL Server, by entering the path to the SQL BINN folder in the text box which says "Path(s) to DLLs" and then clicking the button which says "Get PDB dnld script". The backing code for this is in the repo, where we use the Microsoft.Diagnostics.Runtime.Utilities.PEFile class to get the GUID signature for each binary.

Hope this clarifies.

**Comment by EvanCarroll** [comment]
Not really, I'm using Radare. I'd love to know how you construct the path to download the url because the Radare code is broken for this. Did you figure this out with official documentation (somewhere), a blog link I can read it from? Or do I just dive into the `Microsoft.Diagnostics.Runtime.Utilities.PEFile` and look to re-implement that that in C? I assume there is some kind of method you go from the dll itself, to reading something from it, or hashing it and creating the url with the pdb?

**Comment by arvindshmicrosoft** [comment]
It's part of the PE file header. Check the source for the PEFile class. https://github.com/Microsoft/clrmd

**Comment by EvanCarroll** [comment]
Thanks a ton @arvindshmicrosoft that's precisely what I was looking for. The GUID is in the PE32 header. And that and the name of the file is all that's needed to submit a request to the pdb server.
